// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg4MJagIWD2HZRxI5YhVkpyKnAz3pOP5A',
    appId: '1:697027988940:web:12700c31a2b042becde169',
    messagingSenderId: '697027988940',
    projectId: 'hey-keshaa',
    authDomain: 'hey-keshaa.firebaseapp.com',
    storageBucket: 'hey-keshaa.firebasestorage.app',
    measurementId: 'G-HNK6C58LBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKP75lJ9bP4Bh0M2Bvymc0KG8cAgTJMRY',
    appId: '1:697027988940:android:d417a201ac9595d7cde169',
    messagingSenderId: '697027988940',
    projectId: 'hey-keshaa',
    storageBucket: 'hey-keshaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC05wi7hjXsCyLE8VIxLZQLaz0EjcyKYvY',
    appId: '1:697027988940:ios:12c5c3628f3da6e9cde169',
    messagingSenderId: '697027988940',
    projectId: 'hey-keshaa',
    storageBucket: 'hey-keshaa.firebasestorage.app',
    iosBundleId: 'com.example.heyKeshaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC05wi7hjXsCyLE8VIxLZQLaz0EjcyKYvY',
    appId: '1:697027988940:ios:12c5c3628f3da6e9cde169',
    messagingSenderId: '697027988940',
    projectId: 'hey-keshaa',
    storageBucket: 'hey-keshaa.firebasestorage.app',
    iosBundleId: 'com.example.heyKeshaa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg4MJagIWD2HZRxI5YhVkpyKnAz3pOP5A',
    appId: '1:697027988940:web:2d98f5905157090fcde169',
    messagingSenderId: '697027988940',
    projectId: 'hey-keshaa',
    authDomain: 'hey-keshaa.firebaseapp.com',
    storageBucket: 'hey-keshaa.firebasestorage.app',
    measurementId: 'G-4NJVV4PW16',
  );

}