// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_API_KEY_HERE',
    appId: 'YOUR_APP_ID_HERE',
    messagingSenderId: '697027988940',
    projectId: 'hey-keshaa',
    authDomain: 'hey-keshaa.firebaseapp.com',
    storageBucket: 'hey-keshaa.firebasestorage.app',
    measurementId: 'G-HNK6C58LBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_API_KEY_HERE',
    appId: 'YOUR_APP_ID_HERE',
    messagingSenderId: '697027988940',
    projectId: 'hey-keshaa',
    storageBucket: 'hey-keshaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_API_KEY_HERE',
    appId: 'YOUR_APP_ID_HERE',
    messagingSenderId: '697027988940',
    projectId: 'hey-keshaa',
    storageBucket: 'hey-keshaa.firebasestorage.app',
    iosBundleId: 'com.example.heyKeshaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_API_KEY_HERE',
    appId: 'YOUR_APP_ID_HERE',
    messagingSenderId: '697027988940',
    projectId: 'hey-keshaa',
    storageBucket: 'hey-keshaa.firebasestorage.app',
    iosBundleId: 'com.example.heyKeshaa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_API_KEY_HERE',
    appId: 'YOUR_APP_ID_HERE',
    messagingSenderId: '697027988940',
    projectId: 'hey-keshaa',
    authDomain: 'hey-keshaa.firebaseapp.com',
    storageBucket: 'hey-keshaa.firebasestorage.app',
    measurementId: 'G-4NJVV4PW16',
  );

}